const POSTAL_CODE_AMERICA_LOCALE = 'US';
// const POSTAL_CODE_ARGENTINA_LOCALE = 'AR';
const POSTAL_CODE_BRAZIL_LOCALE = 'BR';
export const POSTAL_CODE_LOCALES = [
  POSTAL_CODE_AMERICA_LOCALE,
  // POSTAL_CODE_ARGENTINA_LOCALE,
  POSTAL_CODE_BRAZIL_LOCALE,
];

const AMERICA_LOCALE = 'en-US';
const ARGENTINA_LOCALE = 'es-AR';
const BRAZIL_LOCALE = 'pt-BR';
export const LOCALES = [
  AMERICA_LOCALE,
  ARGENTINA_LOCALE,
  BRAZIL_LOCALE,
];
